### ISSUE TITLE
xApp does not work

### ISSUE THREAD

**Issue by Ali78k** [srsran/oran-sc-ric#31]
Dear community. I've followed the [instruction](https://docs.srsran.com/projects/project/en/latest/tutorials/source/near-rt-ric/source/index.html) about integrating OSC-RIC and srsRAN, I used main branches for all projects.
I run 5gc, ric, gNb and UE services/processes respectively. but the xApp faced the issue:
```
root@srs:~/oran-sc-ric# docker compose exec python_xapp_runner ./kpm_mon_xapp.py --metrics=DRB.UEThpDl,DRB.UEThpUl --kpm_report_style=5
![Screenshot from 2024-07-21 16-00-39](https://github.com/user-attachments/assets/a29a0dac-9bc6-4694-8a0d-038a329c9d94)
![Screenshot from 2024-07-21 16-00-51](https://github.com/user-attachments/assets/a1aac010-e6fa-44c9-bf6b-4ad1ea454a65)

1721565030056 7/RMR [INFO] ric message routing library on SI95 p=4562 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
INFO: Subscription for E2SM_KPM Report Service Style 5 requires at least two UE IDs -> add dummy UeID: 1
Subscribe to E2 node ID: gnbd_001_001_00019b_0, RAN func: e2sm_kpm, Report Style: 5, UE_ids: [0, 1], metrics: ['DRB.UEThpDl', 'DRB.UEThpUl']
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./kpm_mon_xapp.py", line 91, in start
    self.e2sm_kpm.subscribe_report_service_style_5(e2_node_id, report_period, ue_ids, metric_names, granul_period, subscription_callback)
  File "/opt/xApps/lib/e2sm_kpm_module.py", line 53, in subscribe_report_service_style_5
    self.parent.subscribe(e2_node_id, self.ran_func_id, event_trigger_def, action_def, indication_callback, e2sm_types.E2SM_KPM)
  File "/opt/xApps/lib/xAppBase.py", line 109, in subscribe
    data, reason, status  = self.subscriber.Subscribe(subReq)
  File "/opt/ric-plt-xapp-frame-py/ricxappframe/xapp_subscribe.py", line 101, in Subscribe
    response = self.api.request(method="POST", url=self.uri + "/subscriptions", headers=None, body=subs_params.to_dict())
  File "/opt/ric-plt-xapp-frame-py/ricxappframe/subsclient/api_client.py", line 368, in request
    return self.rest_client.POST(url,
  File "/opt/ric-plt-xapp-frame-py/ricxappframe/subsclient/rest.py", line 269, in POST
    return self.request("POST", url,
  File "/opt/ric-plt-xapp-frame-py/ricxappframe/subsclient/rest.py", line 228, in request
    raise ApiException(http_resp=r)
ricxappframe.subsclient.rest.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 21 Jul 2024 12:30:31 GMT', 'Content-Length': '0', 'Connection': 'close'})

```
and, RIC logs are
```
ric_rtmgr_sim       | 2024/07/21 12:28:33 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"192.168.63.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 34.771µs
ric_submgr          | {"ts":1721565031162,"crit":"ERROR","id":"submgr","mdc":{"CONTAINER_NAME":"ric_submgr","HOST_NAME":"ric_submgr_host","PID":"1","POD_NAME":"submgr_pod","SERVICE_NAME":"ric_submgr_service","SYSTEM_NAME":"oran_sc_ric","time":"2024-07-21T12:30:31"},"msg":"No E2 connection for ranN
ame gnbd_001_001_00019b_0"}

```

The attached pictures show the whole system logs.

Thanks in advance.
Ali
![Screenshot from 2024-07-21 16-00-39](https://github.com/user-attachments/assets/5fd1ed63-1d8f-4ffe-9e61-163b14552747)
![Screenshot from 2024-07-21 16-00-51](https://github.com/user-attachments/assets/e8d546e2-53da-4aa5-85fb-2ad189164678)

**Comment by pgawlowicz** [comment]
note that the gnb e2 agent connects to RIC with id: `gnb_001_001_0000019b`, while the xapp sends a request to `gnbd_001_001_00019b_0`. Please use the ID of the agent.

**Comment by Ali78k** [comment]
Many thanks @pgawlowicz . E2 Setup and RIC Subscription messages are transmitted correctly but RIC Indication messages aren't in a good situation. you can see logs below:
```RIC```
```bash
ric_rtmgr_sim       | 2024/07/22 06:24:37 POST /ric/v1/handles/dissociate-ran  body: [{"E2TAddress":"192.168.63.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 9.83µs
ric_rtmgr_sim       | 2024/07/22 06:24:37 POST /ric/v1/handles/dissociate-ran  body: [{"E2TAddress":"192.168.63.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 18.216µs
ric_rtmgr_sim       | 2024/07/22 06:25:00 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"192.168.63.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 130.665µs
ric_rtmgr_sim       | 2024/07/22 06:25:24 POST /ric/v1/handles/xapp-subscription-handle  body: {"address":"192.168.63.20","port":4562,"subscription_id":5} elapsed: 12.144µs
ric_rtmgr_sim       | 2024/07/22 06:25:47 DELETE /ric/v1/handles/xapp-subscription-handle  body: {"address":"192.168.63.20","port":4562,"subscription_id":5} elapsed: 11.677µs
ric_rtmgr_sim       | 2024/07/22 06:26:01 POST /ric/v1/handles/dissociate-ran  body: [{"E2TAddress":"192.168.63.10:38000","ranNamelist":["gnb_001_001_0000019b"]}] elapsed: 13.011µs
^CGracefully stopping... (press Ctrl+C again to force)

```

```xApp```
```bash
root@srs:~/oran-sc-ric# docker compose exec python_xapp_runner ./kpm_mon_xapp.py --metrics=DRB.UEThpDl,DRB.UEThpUl --kpm_report_style=2
1721629523287 59/RMR [INFO] ric message routing library on SI95 p=4562 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
Subscribe to E2 node ID: gnb_001_001_0000019b, RAN func: e2sm_kpm, Report Style: 2, UE_id: 0, metrics: ['DRB.UEThpDl', 'DRB.UEThpUl']
Successfully subscribed with Subscription ID:  2jaeH8HicHhdVdNHEFAy2HqalfY
Received Subscription ID to E2EventInstanceId mapping: 2jaeH8HicHhdVdNHEFAy2HqalfY -> 5
{'response': 'OK', 'status': 200, 'payload': '{}', 'ctype': 'application/json', 'attachment': None, 'mode': 'plain'}
192.168.63.13 - - [22/Jul/2024 06:25:24] "POST /ric/v1/subscriptions/response HTTP/1.1" 200 -
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
^CUnsubscribe Subscription ID:  2jaeH8HicHhdVdNHEFAy2HqalfY
Successfully unsubscribed from Subscription ID:  2jaeH8HicHhdVdNHEFAy2HqalfY

````

I also attached a pcap file; actually, the result of following command:
```sudo tshark -i any -f "sctp port 36421" -w ./e2ap.pcap```

[capture.tar.gz](https://github.com/user-attachments/files/16329429/capture.tar.gz)

**Comment by Ali78k** [comment]
Thank you all. it works with "test" branch!

**Comment by noelpadgaonkar** [comment]
Dear community,
I hope you are doing well. I am facing this similar issue of following the tutorial on this link: https://docs.srsran.com/projects/project/en/latest/tutorials/source/near-rt-ric/source/index.html . I tried the troubleshooting mentioned such as changing the E2 Node Id as mentioned, but still I am getting the error: 
`ric_submgr            | {"ts":1734632009953,"crit":"ERROR","id":"submgr","mdc":{"CONTAINER_NAME":"ric_submgr","HOST_NAME":"ric_submgr_host","PID":"1","POD_NAME":"submgr_pod","SERVICE_NAME":"ric_submgr_service","SYSTEM_NAME":"oran_sc_ric","time":"2024-12-19T18:13:29"},"msg":"No E2 connection for ranName gnb_001_001_00019b"}`

When I try to run the sudo ./gnb -c ~/oran-sc-ric/e2-agents/srsRAN/gnb_zmq.yaml command, it is stuck on "Attaching UE...". 

Since this is relatively new to me, I would like some guidance  on how I can proceed to resolve this.

Thank you.

**Comment by pgawlowicz** [comment]
@noelpadgaonkar Could you share your gnb config ang logs?

**Comment by noelpadgaonkar** [comment]
Hi @pgawlowicz , can you help me where can I find these? Its all new for me so I would like some assistance. Apologies.

**Comment by noelpadgaonkar** [comment]
I am not sure if you needed this which I am attaching here. 

![image](https://github.com/user-attachments/assets/6025b356-3b83-4e0d-b5a5-3fc05b80d2e6)

**Comment by h57jafari** [comment]
> note that the gnb e2 agent connects to RIC with id: `gnb_001_001_0000019b`, while the xapp sends a request to `gnbd_001_001_00019b_0`. Please use the ID of the agent.

Hi, where we can modify this ID. Thank you.
